# Generated by Django 4.0.2 on 2022-02-27 11:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSpace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='space title')),
                ('price', models.FloatField(blank=True, help_text='Rental price of the space per 1 day in RUB.', validators=[django.core.validators.MinValueValidator(1, 'The rental of the space should be at least 1RUB.')], verbose_name='rental price')),
                ('description', models.TextField(blank=True, help_text='The detailed description of advertisement space. Should include all other important information.', verbose_name='description')),
                ('location', models.CharField(blank=True, help_text='The location of the advertisement space in textual form.', max_length=255, verbose_name='location')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'AdSpace',
                'verbose_name_plural': 'AdSpaces',
                'ordering': ['created'],
            },
        ),
    ]
