# Generated by Django 4.0.2 on 2022-03-04 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_alter_adspace_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adspace',
            options={'ordering': ['-created'], 'verbose_name': 'AdSpace', 'verbose_name_plural': 'AdSpaces'},
        ),
        migrations.AlterField(
            model_name='adspace',
            name='price',
            field=models.FloatField(blank=True, default=None, help_text='Rental price of the space per 1 day in RUB.', null=True, validators=[django.core.validators.MinValueValidator(1, 'The rental of the space should be at least 1RUB.')], verbose_name='rental price'),
        ),
    ]
