# Generated by Django 4.0.2 on 2022-03-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_alter_adspace_options_alter_adspace_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspace',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='adspace',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='longitude'),
        ),
    ]
