# Generated by Django 4.0.2 on 2022-02-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSpaceImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='adspace_images', verbose_name='space image')),
            ],
            options={
                'verbose_name': 'Advertisement space image',
                'verbose_name_plural': 'Advertisement space images',
            },
        ),
    ]
