# Generated by Django 4.0.2 on 2022-02-27 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspaceimage',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spaces.adspace', verbose_name='Advertisement space'),
        ),
    ]
